kind: pipeline
type: docker
name: default

steps:
- name: check-reservations
  image: python:3
  commands:
  - pip install pyjson5
  - cd id-reservations
  - python3 verify.py --order-desc item-ids.json5
